## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

#version: '2.4'

networks:
    br0:
      external: true

services:
  nginx_1.28.0:
    container_name: nginx_1.28.0
    image: chunhui2001/ubuntu_25.10:nginx_1.28.0
    platform: linux/amd64
    mem_limit: 100m
    ports:
      - 8100:80
    #entrypoint: ["/docker-entrypoint.sh"]
    volumes:
      - ./nginx.sample.nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
      - ./nginx.sample.default:/usr/local/nginx/sites-enabled/default:ro
      #- ./nginx.sample.default.ssl:/usr/local/nginx/sites-enabled/default:ro
      #- /my_directories:/usr/local/nginx/html/:rw
    restart: always
    networks:
        br0:
          ipv4_address: 172.16.197.61